# Generated by Django 6.0.3 on 2026-04-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_image', models.ImageField(upload_to='uploads/')),
                ('saree_image', models.ImageField(upload_to='uploads/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='output/')),
            ],
        ),
    ]
